#!/usr/bin/env pwsh
param(
    [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
    [string]$VenvDir = (Join-Path (Resolve-Path (Join-Path $PSScriptRoot "..")).Path ".venv"),
    [string]$PythonCommand = "",
    [string]$TorchIndexUrl = "https://download.pytorch.org/whl/cpu",
    [switch]$Dev,
    [switch]$BootstrapGgml,
    [string]$LlamaCppRoot = "C:\Users\akikf\programing\llama.cpp",
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

function Write-Section([string]$title) {
    Write-Host ""
    Write-Host "=== $title ===" -ForegroundColor Cyan
}

function Invoke-Checked([string[]]$cmd, [string]$label) {
    Write-Host "-> $label" -ForegroundColor Yellow
    if ($DryRun) {
        Write-Host ("   " + ($cmd -join " ")) -ForegroundColor DarkGray
        return
    }
    & $cmd[0] @($cmd | Select-Object -Skip 1)
    if ($LASTEXITCODE -ne 0) {
        throw "$label failed with exit code $LASTEXITCODE"
    }
}

function Invoke-CommandArray([string[]]$cmd) {
    & $cmd[0] @($cmd | Select-Object -Skip 1)
}

function Resolve-PythonCommand {
    param([string]$Preferred)

    if ($Preferred) {
        return $Preferred
    }

    $candidates = @(
        @("python"),
        @("py", "-3.13"),
        @("py", "-3.12"),
        @("py", "-3")
    )

    foreach ($candidate in $candidates) {
        try {
            if (-not $DryRun) {
                Invoke-CommandArray (@($candidate + @("--version"))) 2>$null | Out-Null
                if ($LASTEXITCODE -eq 0) { return $candidate }
            }
        } catch {
        }
    }

    throw "No usable Python command found. Pass -PythonCommand explicitly."
}

function Quote-Command([string[]]$parts) {
    return ($parts | ForEach-Object {
        if ($_ -match '\s') { '"' + $_ + '"' } else { $_ }
    }) -join " "
}

Set-Location $ProjectRoot
Write-Host "Project root: $ProjectRoot" -ForegroundColor Green

$python = Resolve-PythonCommand -Preferred $PythonCommand
$pythonDisplay = Quote-Command $python
Write-Host "Python command: $pythonDisplay" -ForegroundColor Green

Write-Section "Create Virtual Environment"
if (-not (Test-Path $VenvDir)) {
    Invoke-Checked @($python + @("-m", "venv", $VenvDir)) "Create venv"
} else {
    Write-Host "Venv exists: $VenvDir" -ForegroundColor Green
}

$venvPython = Join-Path $VenvDir "Scripts\python.exe"
if (-not (Test-Path $venvPython)) {
    throw "Venv Python not found at $venvPython"
}

Write-Section "Upgrade Packaging Tools"
Invoke-Checked @($venvPython, "-m", "pip", "install", "--upgrade", "pip", "setuptools", "wheel") "Upgrade pip/setuptools/wheel"

Write-Section "Install Torch"
Invoke-Checked @($venvPython, "-m", "pip", "install", "--index-url", $TorchIndexUrl, "torch") "Install torch"

Write-Section "Install Python Requirements"
$requirementsPath = Join-Path $ProjectRoot "requirements.txt"
if (-not (Test-Path $requirementsPath)) {
    throw "requirements.txt not found at $requirementsPath"
}

$filteredRequirements = @()
Get-Content $requirementsPath | ForEach-Object {
    $line = $_.Trim()
    if (-not $line) { return }
    if ($line.StartsWith("#")) { return }
    if ($line -match '^\s*torch([<>=~!].*)?$') { return }
    $filteredRequirements += $line
}

$tempRequirements = Join-Path $env:TEMP "xorzen_requirements.bootstrap.txt"
Set-Content -Path $tempRequirements -Value ($filteredRequirements -join [Environment]::NewLine)
if ($filteredRequirements.Count -gt 0) {
    Invoke-Checked @($venvPython, "-m", "pip", "install", "-r", $tempRequirements) "Install python requirements"
}

if ($Dev) {
    Write-Section "Install Dev Extras"
    Invoke-Checked @($venvPython, "-m", "pip", "install", "pytest", "black") "Install dev extras"
}

Write-Section "Capture Torch CMake Path"
$torchInfo = & $venvPython -c "import torch, json; print(json.dumps({'version': torch.__version__, 'cmake_prefix_path': torch.utils.cmake_prefix_path}))"
if ($LASTEXITCODE -ne 0) {
    throw "Unable to query torch runtime"
}

$torchJson = $torchInfo | ConvertFrom-Json
$torchCmakePath = $torchJson.cmake_prefix_path
Write-Host "Torch version: $($torchJson.version)" -ForegroundColor Green
Write-Host "Torch CMake prefix: $torchCmakePath" -ForegroundColor Green

$depsDir = Join-Path $ProjectRoot ".deps"
New-Item -ItemType Directory -Force -Path $depsDir | Out-Null
$envScript = Join-Path $depsDir "bootstrap-env.ps1"
@"
# Generated by bootstrap_dependencies.ps1
`$env:CMAKE_PREFIX_PATH = "$torchCmakePath"
`$env:Torch_DIR = Join-Path "`$env:CMAKE_PREFIX_PATH" "Torch"
"@ | Set-Content -Path $envScript

if ($BootstrapGgml) {
    Write-Section "GGML Source Check"
    $ggmlRoot = Join-Path $ProjectRoot "extern\ggml"
    $ggmlCore = Join-Path $ggmlRoot "ggml.c"
    if (Test-Path $ggmlCore) {
        Write-Host "GGML already present at $ggmlRoot" -ForegroundColor Green
    } elseif (Test-Path $LlamaCppRoot) {
        Write-Host "GGML source not found. You can copy it from: $LlamaCppRoot" -ForegroundColor Yellow
        Write-Host "Run .\setup_ggml.ps1 after setting its source path, or copy the ggml files manually." -ForegroundColor Yellow
    } else {
        Write-Host "GGML source not found and llama.cpp root missing." -ForegroundColor Red
    }
}

Write-Section "Done"
Write-Host "Environment prepared." -ForegroundColor Green
Write-Host "Source this file before configuring CMake:" -ForegroundColor Cyan
Write-Host "  .\.deps\bootstrap-env.ps1" -ForegroundColor White
Write-Host "Then configure C++ with CMAKE_PREFIX_PATH from the generated env." -ForegroundColor Cyan
